version: '3.8'
services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db_path:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=TRUE
    restart: unless-stopped


  fast-api:
    build:
      context: ./recommend_model #Docker file의 경로 지정
      dockerfile: Dockerfile
    container_name: fast-api
    ports:
      - "8001:8000"
    environment:
      RAW_ROOT: "/data/Validation/01.원천데이터"
      LABEL_ROOT: "/data/Validation/02.라벨링데이터"
      CHROMA_HOST: "${CHROMA_HOST}"
      CHROMA_PORT: "${CHROMA_PORT}"
      AWS_DEFAULT_REGION: "ap-northeast-2"
    depends_on:
      - chromadb
    restart: unless-stopped
    volumes:
      - "${DATA_SOURCE_PATH}:/data/Validation:ro"