version: '3.8'
services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db_path:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=TRUE
    restart: unless-stopped


  fast-api:
    build:
      context: ./recommend_model #Docker file의 경로 지정
      dockerfile: Dockerfile
    container_name: fast-api
    ports:
      - "8001:8000"
    environment:
      DATA_ROOT: "/data"
      # CHROMA_HOST: "chromadb"
      # CHROMA_PORT: "8000"
      # AWS_DEFAULT_REGION: "ap-northeast-2"
    depends_on:
      - chromadb
    restart: unless-stopped
    volumes:
      -"C:\Users\ehjun\Documents\데브코스데이터\temp\008.의류_통합_데이터(착용_이미지,_치수_및_원단_정보)\01-1.정식개방데이터\Validation"

